### ISSUE TITLE
Raise valueerror instead of exception

### ISSUE THREAD

**Issue by tom4everitt** [causalincentives/pycid#20]
(suggested by Eric)

**Comment by edlanglois** [comment]
Many of these exceptions could  removed entirely. Run the "happy-path" and let the code automatically raise an exception when getting to the part that fails. An KeyError from an failing dictionary lookup or an IndexError from a failed array lookup are both pretty reasonable exceptions to be raised from the CID / analyze methods. If we want they can be wrapped with a try-catch to add more explanation.

For reference, this principle is called EAFP: "Easier to Ask Forgiveness than Permission" and is often used in idiomatic Python code, as compared to LBYL: "Look Before You Leap".

Anyways, making this change is slightly more work than just renaming the exceptions and I'm doing other things today but I can make this change on Monday.

**Comment by tom4everitt** [comment]
Interesting. To me it usually seems better to catch an error earlier rather than later. If a method gets an input which it is not meant to handle, as a user it is convenient that this is highlighted immediately, rather than from an error raised far down some submethod. Otherwise you have to dig through a big stack trace, and try to figure out where something went wrong, as opposed to know immediately.

In some cases I definitely agree though. It's not necessary to check that a dictionary has a key that it's supposed to have before accessing it, because the error is pretty self-explanatory. So maybe some of our check are actually redundant, not sure

**Comment by edlanglois** [comment]
Yeah, I agree that it's also nice to fail quickly and be informative about the failures, so its possible to go either way. In the end the only exceptions I removed were the ones that checked whether a node was a decision because those were usually immediately followed by a dictionary lookup that would raise a KeyError if the node isn't a decision.

On the other hand one feature that EAFP often gives you is that you get exactly the failures that are necessary and nothing more. A developer reading the function doesn't have to think about whether a check at the beginning is really required or not, the function will just fail at the part that justifies the failure.

One way to combine EAFP with the informative failures is to catch and re-raise the exception with more context:
```python
def process_node(node: str):
    [do stuff]
    try:
        [something fail if node is invalid]
    except ValueError as e:
        raise ValueError(f"{node} is not in the graph") from e
```

**Comment by tom4everitt** [comment]
Cool, makes sense
