### ISSUE TITLE
AttributeError: module 'pycid' has no attribute 'discrete_uniform'

### ISSUE THREAD

**Issue by JoaoPaulo-Ferreira** [causalincentives/pycid#51]
Hi,

I was reading and following the steps from https://procbuild.scipy.org/download/Jamesfox1-2021 but when I tried to add CPTs to Nodes using the example it gets an error and  the message:  AttributeError: module 'pycid' has no attribute 'discrete_uniform'.  I also tried to clone the repo and run the CID_basics notebook and got the same error.

Any idea of how to fix it?

thanks.

**Comment by Jamesfox1** [comment]
Hi @JoaoPaulo-Ferreira, thanks for alerting me to this. I've had a quick look and you're right I have found the same problem. I will look into this, fix, and push tomorrow (I'm on UK time)!
Thanks again for lodging this issue!

**Comment by Jamesfox1** [comment]
@JoaoPaulo-Ferreira the problem turned out to be caused by newer version of pgmpy (a package that PyCID depends on) rather than anything within PyCID. 

This is annoying and I shall be emailing the pgmpy people (because obviously newer versions of their package shouldn't be causing problems for those who built upon what was the latest version of pgmpy only 2 months ago...)

 To solve this problem for the moment, I've changed the package requirements to forcibly use pgmpy 0.1.13 rather than 0.1.15 (the latest version).
 
 Therefore, everything should now run as expected (including all of the tests, the notebooks, etc).
 
 Do let me know if you encounter any other problems though and thanks for your interest in PyCID!
